creation_rules:
  - gcp_kms: projects/proven-sum-435500-p1/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
    # Specify any file patterns you want to auto-encrypt
    path_regex: 'secrets.yaml$'
    encrypted_regex: '^(data)$'