apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: postgres-db-ns
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXNfdXNlcg==
  POSTGRES_PASSWORD: cG9zdGdyZXNfcGFzcw==
  POSTGRES_DB: bXlkYg==
