apiVersion: v1
kind: Secret
metadata:
    name: postgres-secret
    namespace: postgres-db-ns
type: Opaque
data:
    POSTGRES_USER: ENC[AES256_GCM,data:BzkOUjQRpc8sDPnG2/UHUA0ccqU=,iv:Ckqg8buvtU/5Wa/yJ6UX1u6e0CQBneHKo57Yn4Jt/JI=,tag:/pdE3kKEw0SJFYIlKzceyg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:Q3neNAAtSEosNFSmBMkzToqx9s4=,iv:MsQQfA1S4tAdu0KrJ0lBD/Lh5QZxyd1DIVqpxnYqLLc=,tag:BOCoNxCcLdG8VA6yMre9cw==,type:str]
    POSTGRES_DB: ENC[AES256_GCM,data:Kzvr5kDPaNw=,iv:YiZLVpqoQ3Z29TMnOVSeK8m/rkw0IefyIceM2/h9YQ8=,tag:cra+LOBZu5gPlD+nPyzLUw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/proven-sum-435500-p1/locations/northamerica-northeast1/keyRings/my-keyring/cryptoKeys/my-key
          created_at: "2024-11-19T19:23:14Z"
          enc: CiQAxmrqTunnNupddQK6lgcK0gaHMws82TFfGch6Tzo0APpN9RkSSACZP4Z/Y0LD0kyu99W9loC4/0uF94aTFlwDfTSe4X2uV2x+5GVX3PCGWVtvXtIcLPtwx0CRZBhO1DrL5fWvGWBnOwKOb+17MQ==
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-11-19T19:23:15Z"
    mac: ENC[AES256_GCM,data:MUlrVicGsQAS6NQGQXOLVhPxk/w/gqv/gtXrpD+BMPoUZtPETHDqfTB6XyK4njuNNWoGizXXwTgdS065DW+QgZFxexgF1iYlQ3+GVbW7y+tJvPBlmQGG73O7eImDqH0NNFxsRW7pxBrQ7S3XAjNE1ZVGJK7L+jqzTf1A25n+3+w=,iv:whZua0WdJtrHMka4kk0Jn1nI4PhsoFaHJd5C1Po45P4=,tag:IfjpcItngejHWTSK/MfjbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data)$
    version: 3.9.1
