apiVersion: v1
kind: Namespace
metadata:
  name: flask-app-ns
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-config
  namespace: flask-app-ns
data:
  PGDB_HOST: postgres-service.postgres-db-ns.svc.cluster.local
  PGDB_USER: postgres_user
  PGDB_PASSWORD: postgres_pass
  PGDB_NAME: mydb
  REDIS_HOST: redis-service.redis-cache-ns.svc.cluster.local
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-deployment
  namespace: flask-app-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: yolimar23/flask-app:latest
        ports:
        - containerPort: 5000
        envFrom:
        - configMapRef:
            name: flask-config
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: flask-app-ns
spec:
  selector:
    app: flask
  ports:
  - protocol: TCP
    port: 80
    targetPort: 5000
  type: ClusterIP